### ISSUE TITLE
Node group, Displacement

### ISSUE THREAD

**Issue by kasabiel** [InfinityCg/colorspacer#2] opened 2023-06-30 04:42 UTC
I often use the poliigon add-on, which is a one-click solution to apply textures. 
But your add-on does not work with node groups, even when I tried both engine tag hunter and node train. Is there a way to make your add-on compatible with node groups?
I set a tag on displacement, but it did not work.
 The add-on recognized displacement as normal(noncolor). How can I fix this problem?
Thank you for your time and attention. I look forward to hearing from you soon."

**Comment by InfinityCg** [comment] 2023-06-30 08:57
Hi @kasabiel 
The addon does not yet work with node groups, it only supports open nodes as of the current version
Supported nodes : 

- Principled BSDF: Base color, Emission (Color) | Metallic, Roughness, Specular (Non Color)
- Normal Map: Color (Non Color)
- Bump: Height (Non Color)
- Emission: Color (Color)

The group support is being worked on and might be released with further updates

----------------------------

For the displacement issue, could you elaborate more on that as I am unable to grasp the issue
(a) The engine (b) How is it intended to work (c) How is it working
if the problem is with the tag based engine please also include a screenshot of the addon preferences(Where you set the tags)

Thanks for supporting the addon,  
Yours sincerely,
InfinityCg

**Comment by InfinityCg** [comment] 2023-07-06 12:22
Hi @kasabiel 
Further information is required to diagnose with the issue

**Closed as completed** 2024-03-13 12:50 UTC
Labels: Awaiting further information
